### ISSUE TITLE
Re-add Windows parallel computing instructions

### ISSUE THREAD

**Issue by andrew-vancil** [degauss-org/degauss-org.github.io#23]

**Comment by cole-brokamp** [comment]
this came up again here https://github.com/degauss-org/geocoder/issues/39

**Comment by andrew-vancil** [comment]
Here's the old deleted instructions

https://github.com/degauss-org/degauss-org.github.io/commit/3830289bdb349cd0916ebac0f6872beb9caad087#diff-afd11c699a155b2a7bbc7a8c3004165e5f0cfeccf890b54b103aa445dbefa44e
