### ISSUE TITLE
Binding failing on Windows machine

### ISSUE THREAD

**Issue by stu125** [degauss-org/degauss-org.github.io#4]
A really simple thing that took me too long to recognize.  On Windows , if you've corrected for the PWD variable but still getting a "No such file or directory" error check Settings > Shared Drives and make sure your local drive is shared.  Don't know why this became unchecked on my machine but the local drive won't bind without it.

![image](https://user-images.githubusercontent.com/49403531/115408423-d38ca480-a1be-11eb-9440-332fa951a01d.png)

**Comment by cole-brokamp** [comment]
thanks!  we will put this over in the troubleshooting wiki
