### ISSUE TITLE
broken link for docker desktop installation

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/degauss-org.github.io#41]
via email to me:

> ... I was planning to submit an IT ticket to get Docker downloaded on my NIH laptop. However, the link to the official installation instructions seems to be broken, see the screenshot below.
I was hoping to submit my IT request with as much detail as possible so as to not run into issues with my request being rejected… so I was wondering if you could provide any further guidance about the official installation instructions?
> <img width="1194" alt="image001" src="https://user-images.githubusercontent.com/4367617/225785932-c22f4827-7e08-40ba-8e50-8fe26d7a5596.png">

**Comment by andrew-vancil** [comment]
What would we like this to link to? It looks like we have links to install instructions for both mac and Windows just below that one. Should I remove this link?
