### ISSUE TITLE
expand on navigating the shell and OneDrive

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/degauss-org.github.io#45]
I have had several people with issues using `cd Desktop` recently. 

Some can navigate to Desktop, but their file is not there:
![degauss_errormessage_1](https://user-images.githubusercontent.com/45949235/225938375-1db18c61-d4f8-4126-ba0a-252f5b49d134.PNG)

In another case, after getting a new computer, Desktop wasn't found:
![image001](https://user-images.githubusercontent.com/45949235/225938111-d14991e7-ebf0-4325-a116-47541993acbe.png)

Both of these issues ended up being related to OneDrive. Here is a screenshot of troubleshooting instructions that were successful in helping users find the actual path of their Desktop (related to the second screenshot, above):
<img width="751" alt="image001" src="https://user-images.githubusercontent.com/45949235/225938627-9c170f83-9d74-445c-9c39-32bde30ebb58.png">

`cd Desktop` was meant to simplify the process of navigating to a working directory, but it seems recent Windows changes have made this less straightforward, as the physical Desktop users see is now actually part of OneDrive. We may need to think more about the most streamlined suggestions for this moving forward, or at least add this troubleshooting information to the site (may also want to include a bit about using `ls`/`dir` to see if their file is where it is expected to be).

**Comment by cole-brokamp** [comment]
add to (or refer to this issue) in the PWD section of Troubleshooting?
