### ISSUE TITLE
updates for PWD binding on windows

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/degauss-org.github.io#5]
Are the suggestions raised here integrated yet?  https://github.com/degauss-org/geocoder/issues/6#issuecomment-809653983

I've changed the wiki on geocoding here to just point directly to degauss.org/geocoder.  But I do want to make sure that our Windows-specific `-v` instructions are up to date.

Also, I've seen a couple people comment that the Docker settings might not look like what we have here.  Can we make sure the screenshots are the most up to date?

**Comment by andrew-vancil** [comment]
I think it will be helpful to add a note about using the {pwd} or {PWD} format, as well. That's how we've been sending instructions to Kris for her containers. Side note - do we do a pull request for wiki items or just edit online?

**Comment by cole-brokamp** [comment]
You can edit wiki directly.  Although it is stored in github, it is not a part of the git repo for the code base.

**Comment by andrew-vancil** [comment]
I've added Erika's examples for using the different notation in Windows to the wiki page. 

I was going to update the screenshot for the parallel computing and add a section about allocating more RAM, but I stumbled on a interesting bit that I didn't know about. When Docker on Windows is installed using the WSL 2 engine [which uses a Microsoft built Linux kernel](https://docs.docker.com/docker-for-windows/wsl/), you don't have the option to adjust resource allocation. When you use the older [Hyper-V backend](https://docs.docker.com/docker-for-windows/), you are able to adjust it. There appears to be a way to allocate more memory when using [a WSL 2 build](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig), but it is a bit more complicated.

I don't know if we've run into many memory issues with Windows users, so I wasn't sure if this would be useful information to add to the wiki.

**Comment by cole-brokamp** [comment]
Yes, this makes total sense.  I guess we should point to how to change RAM using WSL since I think most people will be using it this way.  I think WSL might solve some of the `PWD` problems too.

We've talked about somehow putting in a code check for RAM avail to R and customizing a specific threshold for each application, but this would change based on the size of the input data.
