### ISSUE TITLE
Service wrapper

### ISSUE THREAD

**Issue by citrusboy** [degauss-org/degauss-org.github.io#7]
We are interested in possibly wrapping a service around DEGAUSS to allow clients to pass an address to a RESTful web service call and receive back lat/long data as well as ADI scores, for example.

Is there a version of DEGAUSS that includes such a service?

Thanks,
Dan

**Comment by cole-brokamp** [comment]
Hi Dan,

I would recommend looking at https://github.com/degauss-org/geocoder_slim.  You could use this to stand up an API for the geocoding information, but would have to add on any census tract data you want to include.  You can get an idea of how we have implemented it in an R wrapper here: https://github.com/geomarker-io/OfflineGeocodeR

Thanks,
Cole

**Comment by cole-brokamp** [comment]
Although looking at it now, I should mention that the "geocoder_slim" relies on an older version of degauss/geocoder.  It may be possible to use degauss/geocoder:3.0 to achieve the same effect.

**Comment by cole-brokamp** [comment]
Hi Dan,

Please check out this post that I just added to the DeGAUSS wiki on how to use the docker container as an API of sorts: https://github.com/degauss-org/degauss-org.github.io/wiki/Using-DeGAUSS-as-a-Geocoding-API. I hope this helps, please reopen with any questions.

**Comment by citrusboy** [comment]
Thanks, Cole, we'll take a look.
