### ISSUE TITLE
Trouble Shooting Schwartz Error - error in fetching pollutant files 

### ISSUE THREAD

**Issue by iyannan** [degauss-org/degauss-org.github.io#9]
![error1](https://user-images.githubusercontent.com/86365554/123118342-8ae8a600-d410-11eb-8918-317b8357e6d3.png)
![error2](https://user-images.githubusercontent.com/86365554/123118364-91771d80-d410-11eb-8fcd-1d8fdae2963c.png)
![image](https://user-images.githubusercontent.com/86365554/123134524-dc982d00-d41e-11eb-8d66-3dc6adb18277.png)

Attached are the pictures of the error that occurs. The program runs fine if I use a small dataset, around 5 entries. But if I try to increase the input to 10 entries or my entire dataset, this error keeps occurring. degauss/schwartz_grid_lookup:0.4.1 works fine, the error only occurs with degauss/schwartz:0.5.1. Sometimes the error pops up as soon as the program begins to run (error 2 picture), other time the program will run for 20 minutes and then crash half way through downloading the files (error 1 or 3 picture).
 

Here's a sample data set that crashes:
[error_schwartz_site_index.xlsx](https://github.com/degauss-org/degauss-org.github.io/files/6703511/error_schwartz_site_index.xlsx)

**Comment by cole-brokamp** [comment]
Hi Nidhi,  I'm just getting back to this after being gone for a week.  This problem is still persisting, right?

**Comment by cole-brokamp** [comment]
Are you working on a VPN or research network?  These often cause problems with SSL security certificates passing through the Docker container.  You could try to run on a public network or CCHMC guest network.

**Comment by erikarasnick** [comment]
@cole-brokamp  All files downloaded for me with Nidhi's example dataset using degauss/schwartz:0.5.1. 

@iyannan Let us know if trying on different network helps.

**Comment by erikarasnick** [comment]
@iyannan Also, we have made some updates to the container. These updates were not directly related to your issue, but you can now use degauss/schwartz:0.5.4
